<?php

namespace ContainerMFCRuCc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sqzx_KaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sqzx.Ka' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sqzx.Ka'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'headTitleHelper' => ['privates', 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle', 'getHeadTitleService', false],
        ], [
            'headTitleHelper' => 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle',
        ]);
    }
}
