pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    content:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 250
                                    forceResize: false
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 450
                                    forceResize: false
                        medias: {  }
                        name: content
                        description: 'Content area images'
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1745284247
                        creationDate: 1745269014
                        preserveAnimation: false
