pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    content:
                        items: {  }
                        medias: {  }
                        name: content
                        description: 'Content area images'
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1745269069
                        creationDate: 1745269014
                        preserveAnimation: false
