pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    hero-image:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 360
                                    forceResize: false
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 960
                                    forceResize: false
                        medias: {  }
                        name: hero-image
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1745355692
                        creationDate: 1745355661
                        preserveAnimation: false
