<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH36LoXL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH36LoXL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH36LoXL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH36LoXL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH36LoXL\App_KernelDevDebugContainer([
    'container.build_hash' => 'H36LoXL',
    'container.build_id' => '0ea9eed2',
    'container.build_time' => 1745370469,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH36LoXL');
