<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4JQAF4V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4JQAF4V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4JQAF4V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4JQAF4V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4JQAF4V\App_KernelDevDebugContainer([
    'container.build_hash' => '4JQAF4V',
    'container.build_id' => 'ad0a6b22',
    'container.build_time' => 1745348790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4JQAF4V');
