<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZM5PLs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZM5PLs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZM5PLs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZM5PLs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZM5PLs\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZM5PLs',
    'container.build_id' => '751165ff',
    'container.build_time' => 1745356290,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZM5PLs');
